version: 0.1

phases:
  install:
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn build
  post_build:
    commands:
      - echo looking for created dist build
      - ls
      - echo srcdir $SRC_DIR
      - echo codebuildsrcdir $CODEBUILD_SRC_DIR
      - echo Build completed on `date`
      - echo current dir in post build
      - pwd
      - cd $CODEBUILD_SRC_DIR
      - ls
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - dist/**
    - **/dist/**/?(*.js|*.jsx|*.html)
    - server.js
    - package.json
    - $(Build.SourcesDirectory)
 # discard-paths: yes
